### ISSUE TITLE
Line 125 + 155 

### ISSUE THREAD

**Issue by hkrhoads** [DubuqueSeniorCS/DubuqueCoders#14]
Should the semi-colon come before the brackets?

**Comment by ctjet** [comment]
Since these lines are the termination of an array, no. If I create a new array like this:

int ary [] = {1,2,3,4,5};

it makes a new array of length 5 that has 5 numbers already installed. It's a quick way of writing 
int ary [5];
ary[0] = 1;
ary[1] = 2;
ary[2] = 3;
ary[3] = 4;
ary[4] = 5;

because it is creating an array, the semi-colon comes after.
